{
  "comments": [
    {
      "key": {
        "uuid": "f12feee6_d6827d92",
        "filename": "tests/docsis_lib/docsis.py",
        "patchSetId": 1
      },
      "lineNbr": 226,
      "author": {
        "id": 1016854
      },
      "writtenOn": "2019-08-16T12:23:24Z",
      "side": 1,
      "message": "Hi Matthew should I enhance this failure message?",
      "range": {
        "startLine": 226,
        "startChar": 15,
        "endLine": 226,
        "endChar": 42
      },
      "revId": "efa6ec99c4b6afae3f0c9c0e226f5ea670076fab",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}